# config/packages/security.yaml

security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_redirect
            logout:
                path: app_logout
                target: app_login
      
    access_control:
        - { path: '^/user', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/profile', roles: IS_AUTHENTICATED_FULLY }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
