vich_uploader:
    db_driver: orm
    metadata:
            type: attribute

    mappings:
        art:
            uri_prefix: /images/offer/art
            upload_destination: '%kernel.project_dir%/public/images/offer/art'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
