vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: uploads//images/users
            upload_destination: '%kernel.project_dir%/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        art:
            uri_prefix: /images/offer/art
            upload_destination: '%kernel.project_dir%/public/images/offer/art'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
            type: attribute

