vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: uploads//images/users
            upload_destination: '%kernel.project_dir%/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
